// This is my first JavaScript Code!
console.log('Hello World!');

// Variables
let name = 'Shyam';
console.log(name);

// Cannot be reserved Keywords (let, if, else..)
// Should be meaningful
// Cannot start with a number
// Cannot contain a space or hyphen
// Case-sensitive
// Declare variables in Single Line

// Constants

const interestrate = 0.3;
interestrate = 1;
console.log(interestrate);

//Primitive Types

let name = 'Shyam'; // String
let age = 31; // Number
let isApproved = true; // Boolean
let firstname = undefined; // Undefined
let lastname = null; // Clearing a Variable

// Objects

let person = {
    name: 'Shyam',
    age: 31
};

// Dot Notation

person.name = 'John';

console.log(person.name);

// Bracket Notation

person['name'] = 'Sundar';

// Arrays

